title: Null Hypothesis Podcast
description: >-
  Null Hypothesis is a podcast hosted by River Jiang and Robyn Edgar, aiming to provide a deep dive into the latest in scientific understanding -- with all its revelations, nuances, and contradictions. Our first miniseries is about the science of Ageing.
baseurl: ""
url: "http://nullhypothesis.ca"

# Build settings
markdown: kramdown
plugins:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
