title: Null Hypothesis Podcast
description: >-
  Null Hypothesis is a podcast hosted by River Jiang and Robyn Edgar, aiming to provide a deep dive into the latest in scientific understanding.
baseurl: ""
url: "http://nullhypothesis.ca"
permalink: /:categories/:title/

podcast_title: Null Hypothesis with Robyn Edgar and River Jiang
podcast_album_art: /assets/NullHypoSquarelogo.png
podcast_author: Robyn Edgar and River Jiang
podcast_explicit: clean
podcast_email: contact@nullhypothesis.ca
podcast_subtitle: The Ageing Series
podcast_category: Science &amp; Medicine
podcast_subcategory_one: Medicine
podcast_subcategory_two: Natural Sciences

# Build settings
markdown: kramdown
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
